In [6]:
import tensorflow as tf

# Example dataset of image file paths
image1 = './datasets/dataset/0/0_1.jpg'
image2 = './datasets/dataset/0/0_2.jpg'

file_paths = [image1, image2]
ds = tf.data.Dataset.from_tensor_slices(file_paths)

# Step 1: Read the image files as byte strings
ds = ds.map(lambda path: tf.io.read_file(path))

# Step 2: Apply _imread to process each image
_imread = lambda xx: (tf.cast(tf.image.decode_image(xx, channels=3), "float32") - 127.5) * 0.0078125
ds = ds.map(_imread)

# Check a sample output
for img in ds.take(1):
    print(img.shape)  # Output shape of the image tensor
    print(img.numpy())  # Normalized pixel values in the range [-1, 1]


(2604, 4624, 3)
[[[-0.37890625 -0.23828125 -0.14453125]
  [-0.40234375 -0.26171875 -0.16796875]
  [-0.41796875 -0.27734375 -0.18359375]
  ...
  [-0.43359375 -0.41796875 -0.42578125]
  [-0.44140625 -0.42578125 -0.43359375]
  [-0.45703125 -0.44140625 -0.44921875]]

 [[-0.40234375 -0.26171875 -0.16796875]
  [-0.41796875 -0.27734375 -0.18359375]
  [-0.42578125 -0.28515625 -0.19140625]
  ...
  [-0.44140625 -0.42578125 -0.43359375]
  [-0.44921875 -0.43359375 -0.44140625]
  [-0.46484375 -0.44921875 -0.45703125]]

 [[-0.42578125 -0.28515625 -0.19140625]
  [-0.42578125 -0.28515625 -0.19140625]
  [-0.42578125 -0.28515625 -0.19140625]
  ...
  [-0.44921875 -0.44921875 -0.44921875]
  [-0.45703125 -0.45703125 -0.45703125]
  [-0.46484375 -0.46484375 -0.46484375]]

 ...

 [[ 0.26171875  0.11328125 -0.01953125]
  [ 0.26171875  0.11328125 -0.01953125]
  [ 0.25390625  0.10546875 -0.02734375]
  ...
  [-0.50390625 -0.39453125 -0.30859375]
  [-0.51171875 -0.40234375 -0.31640625]
  [-0.51171875 -0.40234375 -

In [2]:
import tensorflow as tf

# Define the lambda function as given
_imread = lambda xx: (tf.cast(tf.image.decode_image(xx, channels=3), "float32") - 127.5) * 0.0078125

# Step 1: Read the image file into a byte string
image_path = './datasets/dataset/0/0_1.jpg'
image_bytes = tf.io.read_file(image_path)

# Step 2: Pass the byte string to `_imread`
processed_image = _imread(image_bytes)

# Check the shape and dtype of the processed image
print(processed_image.shape)  # e.g., (height, width, 3)
print(processed_image.dtype)   # should be float32
print(processed_image.numpy())  # the pixel values should now be in the range [-1, 1]


(2604, 4624, 3)
<dtype: 'float32'>
[[[-0.37890625 -0.23828125 -0.14453125]
  [-0.40234375 -0.26171875 -0.16796875]
  [-0.41796875 -0.27734375 -0.18359375]
  ...
  [-0.43359375 -0.41796875 -0.42578125]
  [-0.44140625 -0.42578125 -0.43359375]
  [-0.45703125 -0.44140625 -0.44921875]]

 [[-0.40234375 -0.26171875 -0.16796875]
  [-0.41796875 -0.27734375 -0.18359375]
  [-0.42578125 -0.28515625 -0.19140625]
  ...
  [-0.44140625 -0.42578125 -0.43359375]
  [-0.44921875 -0.43359375 -0.44140625]
  [-0.46484375 -0.44921875 -0.45703125]]

 [[-0.42578125 -0.28515625 -0.19140625]
  [-0.42578125 -0.28515625 -0.19140625]
  [-0.42578125 -0.28515625 -0.19140625]
  ...
  [-0.44921875 -0.44921875 -0.44921875]
  [-0.45703125 -0.45703125 -0.45703125]
  [-0.46484375 -0.46484375 -0.46484375]]

 ...

 [[ 0.26171875  0.11328125 -0.01953125]
  [ 0.26171875  0.11328125 -0.01953125]
  [ 0.25390625  0.10546875 -0.02734375]
  ...
  [-0.50390625 -0.39453125 -0.30859375]
  [-0.51171875 -0.40234375 -0.31640625]
  [-0.511